### ISSUE TITLE
Extend cypress test coverage

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#1473]
The cypress tests should cover as much of the apps functionality as possible to reduce QA time for releases.
The following is non-exhaustive list of improvements/additions:

- [ ] ~~test all possible navigations: shortcuts, sidebar, buttons (eg the follow project modal can be opened in 3 different ways, but only opening via the button on empty project list is tested)~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1571
- [ ] ~~add tests in a separate file for the profile view to check for all it's content~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1576
  - ~~header contents~~
  - ~~sidebar avatar~~
  - ~~networking icon (might move into a separate test file, if the functionality is extended)~~ -> https://github.com/radicle-dev/radicle-upstream/pull/1559
  - ~~projects and following tab (empty and filled)~~
- [ ] ~~add tests for the project header contents (forked or followed)~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1577
- [ ] ~~cover all elements of the settings page~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1572
  - ~~static content (version, devices, legal, feedback)~~
  - ~~network: list/add/remove seed~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1570
- [ ] ~~test that features are correctly hidden by feature flag~~ -> https://github.com/radicle-dev/radicle-upstream/issues/1569

**Comment by geigerzaehler** [comment]
We need to break this down and prioritize the items.

**Comment by rudolfs** [comment]
It would be great if we could make sure that all the steps (except networking, which is covered by: https://github.com/radicle-dev/radicle-upstream/issues/1529) in the [manual QA procedure](https://github.com/radicle-dev/radicle-upstream/blob/master/QA.md) are covered by this issue or its broken down counterparts.

**Comment by rudolfs** [comment]
This issue was broken down into smaller issues.
