### ISSUE TITLE
Overview: Identities I

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#175]
This issue tracks all of the work (including dependencies) which has to be done to complete the [Basic User Identity](https://www.notion.so/monadic/Basic-User-Identity-0688a802e65040778a459892d6922919) spec.

#### Open questions
  - proxy: when you register your handle, but you pick a different one from the one you picked at identity creation, what should happen with the old/new handle?

### UI
  - [x] copy-to-clipboard entity id component (#180)
  - [x] emojicon generation module (#181)
  - [x] implement onboarding flow screens (#182)
  - [x] implement profile page screens (#186)
  - [x] wire up onboarding and profile screens with app boot logic (#183)
    - [x] fix: navigation from identity creation flow to registering - on cancel/finish, jumps to start of identity flow
  - [x] do not query avatar in user registration flow (#230)
    - [x] proxy: use id to generate the avatar fallback (instead of handle), (the endpoint for querying only     
    - [x] the avatar of a handle will still be needed for org registration)
    - [x] ui: remove avatar query from the user registration modal, always use the avatar fallback of the identity (#276)
  - [x] redo empty profile project page (restyle to match current design) (#263)
  - [x] fix: copy-to-clipboard for identity card (identity creation flow) (#263)
  - [x] fix: use shareable entity identifier for profile `...` dropdown copy-to-clipboard (#263)
  - [x] fix: unregistered project avatar heading (#263)
  - [x] adjust create project flow for local projects to new design & flow (#264)
  - [x] fix: use shareable entity identifier for project and projects listing `...` dropdown copy-to-clipboard (#393)
  - [ ] ~~handle registration: get transaction costs from proxy (#391)~~ will do them when registry will provide them
  - [x] when everything is integrated, write end-to-end tests for the whole identity creation flow (#184)

### Proxy
  - [x] define UI ↔ proxy API (#176)
  - [x] implement mock endpoints (#177)
  - [x] integrate real functionality into API by replacing mock endpoints (#185)
  - [x] switch avatar generation to id(#230)
  - [x] create identity query should return the correct avatarFallback or avatarUrl (it returns the same hardcoded avatar for every handle)
  - [x] integrate identity (the identity should be persisted on refresh or app reboot)
  - [ ] ~~handle registration: endpoint for transaction costs for handle registration (#391)~~
  - [x] add shareable entity identifier to `project` and `projects` endpoints  (#393)

For more info see #171

**Comment by MeBrei** [comment]
>  create identity query should return the correct avatarFallback or avatarUrl (it returns the same hardcoded avatar for every handle)

Currently the identity id is hardcoded

**Comment by rudolfs** [comment]
There's one final integration left: https://github.com/radicle-dev/radicle-upstream/issues/215 to complete `Identities I` and we're tracking it with the milestone.
