### ISSUE TITLE
Cycle plan: May 17 - June 26.

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1893]
This plan captures our work from the week of May 17 till the week of June 26.

## Plan Items

Below is a summary of the top level plan items.

### Patches
Ship a first iteration of patches, a way for users to contribute to projects. 
Read about the thinking -> [community post](https://radicle.community/t/feature-update-revisions/483)
Follow the progress -> #1682 

- [ ] 🔴 Automatic following of peers 
- [x] 🏃 Update the UI automatically when users create a new patch in git #1821 
- [ ] 💪 Think about how to pull from the maintainer (dropdown) #1842 
- [x] 🏃 Write docs https://github.com/radicle-dev/radicle-docs/pull/141 @juliendonck 
- [x] User testing

**Launch checklist**
- [x] remove `isDev()`-flag
- [x] Cut release
- [x] merge docs PR https://github.com/radicle-dev/radicle-docs/pull/141
- [x] Create issue for peer ID's that is reference in `CONTRIBUTING.md`
- [x] merge `CONTRIBUTING.md` PR #1935 
- [x] Share release notes in discord

### Wallet
Currently the wallet is hidden in the user profile (experimental mode), the goal of this is to promote it to a top level sidebar item and have the wallet setup (link eth address + attest with Radicle ID) be part of the onboarding. 
-> [See the design](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=8727%3A133034)
-> [follow the progress](https://github.com/radicle-dev/radicle-upstream/pull/1900)

- [x] 🔴 Split wallet out of profile screen
- [x] Onboarding
  - [x] 🔴 Add wallet setup as optional step (eth address + attestation)
  - [x] 🔴 Have set up on wallet page if skipped
- [ ] Attestation
  - [x] Make 2 way attestation 1 step #1889 
  - [ ] 🔴 🎨 show eth address on profile after attested @brandonhaslegs 
- [x] Move tx center to wallet page
- [x] 🔴 hover state on wallet sidebar icon #1930 

### Orgs
Radicle Orgs allow a group of people to manage multiple projects on Radicle. [Read more](https://radicle.community/t/feature-update-orgs/2132) about orgs.
Design references are -> [here](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=8225%3A3).
Follow the progress -> [here](https://github.com/radicle-dev/radicle-upstream/pull/1813).

- [x] Routing for all the org screens
- [x] Create org flow
- [x] List orgs in sidebar
  - [x] Show org avatar based on Eth address
- [x] Org view
  - [x] Projects tab
    - [x] Create project anchor modal flow
    - [x] Show a list of anchored projects projects
    - [x] Show pending project anchoring
  - [x] Members tab
    - [x] Query gnosis safe quorum metadata "managed by gnosis safe quorum 3/6 bar"
    - [x] Show radicle-link username/avatar for attested members @CodeSandwich
- [ ] Show org ENS name in org header when present
- [ ] Org search

#### Org related prep work
- [x] Port radicle-avatar from rust to typescript https://github.com/radicle-dev/radicle-avatar/pull/5
- [x] Re-deploy everything on rinkeby, because Gnosis Safe only has a test UI on that network
  - [x] Re-reploy funding contracts on rinkeby
  - [x] Re-deploy attestation contracts on rinkeby
  - [x] Re-deploy org contracts on rinkeby
  - [x] Deploy org index for rinkeby on the graph
  - [x] Integrate rinkeby network in the app so we can select it
  - [x] Troubleshoot [GnosisSafe index on rinkeby](https://thegraph.com/explorer/subgraph/radicle-dev/gnosis-safe-rinkeby) -> [it's not supported on rinkeby](https://github.com/gjeanmart/gnosis-safe-subgraph/pull/1#issuecomment-843414489), we'll have to figure out a different way to test the external links to the Gnosis Safe UI

#### Release
- [x] Deploy all Org related contracts on mainnet
- [x] Deploy all Org related indexers on mainnet
- [x] Integrate mainnet in the app
- [ ] Make orgs available without a feature flag

#### Clean up / nice-to-haves
- [ ] 💪 Make other user profiles work https://github.com/radicle-dev/radicle-upstream/issues/1874

### Engineering tasks
- [x] Fast file keystore for development (#1614). We want to reduce the development build times from three minutes down to less than 30 seconds.
- [x] Better router implementation (https://github.com/radicle-dev/radicle-upstream/pull/1876): type safety and more control on when and how things get rendered.

### Design tasks
- [x] Make attestation an optional part of onboarding #1885 
- [ ] Come up with a solution to show following and your projects on the same page #1887 
- [x] Move "Manage Remotes" into its own button? #1866 
- [x] Add What's New popup #1865 
- [x] Project deletion #1884 

### Bugs to be fixed
- [x] *add bugs here*

---

**Legend of annotations**
| Mark | Description |
|------|-------------|
| 🏃 | work in progress |
| ✋ | blocked task |
| 💪 | stretch goal for this iteration |
| 🎨 | design needed |
| 🔴 | missing issue reference |
| 🔵 | more investigation required to remove uncertainty |
| ⚫ | under discussion within the team |
| ⬛ | a large work item, larger than one iteration |

**Comment by juliendonck** [comment]
Sync point:
- can we use patches? Or duplicate gh PR's in radicle
-

**Comment by rudolfs** [comment]
Ideas for next cycle:
  - see if we can get the windows pr over the finish line https://github.com/radicle-dev/radicle-upstream/pull/1623

**Comment by brandonhaslegs** [comment]
I'd like to get #1803 done. It's the last of the main UI customization features.

**Comment by rudolfs** [comment]
### Follow-ups for orgs

#### Known bugs
- [ ] refresh looses focus on org, goes back to profile
- [ ] member attestations not working due to replication issues https://github.com/radicle-dev/radicle-link/issues/708 -> https://github.com/radicle-dev/radicle-upstream/pull/2028/

#### Code review leftovers
- [ ] refactor org data layer https://github.com/radicle-dev/radicle-upstream/issues/2025
- [ ] add tests for serialisation functions https://github.com/radicle-dev/radicle-upstream/issues/2001
- [ ] drop ropsten test net
- [ ] how do we test this feature?

#### Documentation
- [ ] a user guide for [docs.radicle.xyz](https://docs.radicle.xyz) is being worked on by @abbey-titcomb & @brandonhaslegs 

#### Feature improvements
- [ ] don’t poll Ethereum account data https://github.com/radicle-dev/radicle-upstream/issues/1916
- [ ] make upstream follow wallet's network https://github.com/radicle-dev/radicle-upstream/issues/2002
- [ ] show registered Org ENS name
  - [ ] org search
- [ ] how do we show anchors in the project source browsing screen? https://github.com/radicle-dev/radicle-upstream/issues/1976
- [ ] deep-link directly to a specific pending Gnosis transaction -> https://github.com/gnosis/safe-react/issues/970
- [ ] deep-link directly to the Gnosis settings Owners tab

##### Open questions
- is it possible to show user readable anchoring data on the Gnosis pending transaction page?
- should we maybe let users use their own infura account via settings?

#### Roll-out
- [ ] test on mainnet
- [ ] remove feature flag
- [ ] release
- [ ] onboard earlybirds
- [ ] announce publicly

**Comment by juliendonck** [comment]
New cycle plan here: #2049
