### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#202]
All of the work which has to be done to complete the [User registration](https://www.notion.so/monadic/User-Registration-6bcb1ebd6f334d0290c95c5a05f54649) spec.

- [x] UI
  - [x] user registration modal (#216)
  - [x] modal follow ups
    - [x] wire up identity store (#252)
    - [x] open modal via buttons & remove the temp. hotkey (after new identity profile) (#232)
    - [x] add tests for availability of handles (after mocks replacement)
  - [x] show pending transactions
    - [x] transaction icons (#235)
    - [x] transaction center (#242)
    - [x] transaction detail view (#242)
    - [x] ~~transaction storage and reactivity of transaction center~~ (moved to #307)
    - [x] ~~transaction center animations (slide up/down of cards, slide in of center on first transaction)~~ (moved to #307)
    - [x] ~~implement status/progress/error & transaction costs after proxy changes~~ (moved to #225)
- [x] proxy
  - [x] define GraphQL schema for User Registration (#198)
  - [x] implement mock endpoints
  - [x] implement transaction endpoints
  - [x] integrate real functionality into API by replacing mock endpoints

Partially depends on #175
