### ISSUE TITLE
Orgs follow-up work

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2047]
#### Known bugs
- [ ] app reload looses focus on org, goes back to profile https://github.com/radicle-dev/radicle-upstream/issues/2168
- [x] sometimes connecting to wallet isn't working https://github.com/radicle-dev/radicle-upstream/issues/2048 -> https://github.com/radicle-dev/radicle-upstream/issues/2052

#### Code review leftovers
- [ ] add tests for serialisation functions https://github.com/radicle-dev/radicle-upstream/issues/2001
- [x] drop ropsten test net https://github.com/radicle-dev/radicle-upstream/pull/2032

#### Feature improvements
- [x] hide sticky notifications after user has signed or confirmed a transaction in their wallet https://github.com/radicle-dev/radicle-upstream/pull/2044
- [ ] Improve wording around pending anchor execution https://github.com/radicle-dev/radicle-upstream/issues/2092
- [x] Use button component for add org button in sidebar https://github.com/radicle-dev/radicle-upstream/issues/2073
- [ ] org search
- [ ] deep-link directly to a specific pending Gnosis transaction -> https://github.com/gnosis/safe-react/issues/970
- [ ] deep-link directly to the Gnosis settings Owners tab
- [ ] would be nice if the anchor and member lists would update automatically if the user is on that respective tab
- [ ] improve performance:
  - [ ] consolidate gnosis safe and radicle orgs the graph subgraphs into one, to only do one network request instead of 2 https://github.com/radicle-dev/radicle-upstream/issues/2169
  - [ ] reduce the amount of requests we make to the backend to get all data for orgs and single org views https://github.com/radicle-dev/radicle-upstream/issues/2108
  - [ ] poll orgs subgraph less frequently (poll it once every 2s only when org creation is in progress) https://github.com/radicle-dev/radicle-upstream/issues/2171

**Comment by brandonhaslegs** [comment]
Can you add #2073 to this? 😇

**Comment by rudolfs** [comment]
@brandonhaslegs added.

**Comment by juliendonck** [comment]
Moved ENS integration into it's own issue #2147

**Comment by rudolfs** [comment]
Closing this, as most of the relevant items are captured in issues.
