### ISSUE TITLE
Cycle plan: June 28 - July 24

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2049]
This plan captures our work from the week of June 28 till the week of July 24.

## Plan Items

Below is a summary of the top level plan items.

#### Iterations on search
Depending on people search and org search
- [ ] Update error state #1456 

#### Navigate to someone else's profile & redesign the profile page
- [ ] ✋ Make other user profiles work https://github.com/radicle-dev/radicle-upstream/issues/1874
- [ ] ✋ Show attested radicleID on profile and in app #1920 #2091 
- [ ] Come up with a solution to show following and your projects on the same page #1887 

#### Polish orgs
- [x] Member attestations not working due to replication issues https://github.com/radicle-dev/radicle-link/issues/708 -> https://github.com/radicle-dev/radicle-upstream/pull/2028/
- [x] Refactor org data layer https://github.com/radicle-dev/radicle-upstream/issues/2025
- [x] a user guide for [docs.radicle.xyz](https://docs.radicle.xyz) is being worked on by @abbey-titcomb & @brandonhaslegs 
- [ ] Don’t poll Ethereum account data https://github.com/radicle-dev/radicle-upstream/issues/1916
- [ ] Make upstream follow wallet's network https://github.com/radicle-dev/radicle-upstream/issues/2002
- [ ] 💪 How do we show anchors in the project source browsing screen? https://github.com/radicle-dev/radicle-upstream/issues/1976
- [x] Retry on The Graph requests on 502 errors (#2042 @geigerzaehler)
- [x] rollout checklist
  - [x] test on mainnet -> create org 30$, anchor a project 6$, changing members in an org 2$
  - [x] remove feature flag
  - [x] release
  - [x] onboard earlybirds
  - [x] announce publicly

#### Test Ethereum features
- [ ] Write some basic smoke tests for Ethereum related features (orgs, attestations, or token streams) #1921 (@geigerzaehler)
- [ ] 💪 Expand test coverage to orgs (@geigerzaehler)
- [ ] 💪 Test funding pool feature #1581  (@geigerzaehler)

#### Iterate on, polish & ship Token Streams
- [ ] #1943 

---

### Clean up / nice-to-haves
- [ ] patches cleanup
  - [ ] Think about how to pull from the maintainer (dropdown) #1842  (@geigerzaehler)
  - [ ] Automatic following of peers  (@geigerzaehler)
- [ ] #2091
- [ ] Improve importing of branches on importing a existing project #2045 

---

### Engineering tasks
- [x] Improve Ethereum infrastructure in the code base (#1921 @geigerzaehler)
  We’ve seen a lot of additions and changes to Ethereum-related features. This has exposed some shortcomings in the current code that we need to address. This will also be required to properly write tests for Ethereum feature.
- [ ] 💪 Continue improving routing
We want data fetching to happen before the app navigates to a new view. We've implemented this already for the upcoming Orgs feature, and we'd like to port this to other areas of the app as well. (#1596)
- [x] Dependency License Audit #2024  (@geigerzaehler)
- [ ] Improve long load times #1975  (@geigerzaehler)

---

### Design tasks
- [ ] #2100
- [ ] Restyling links #1967 
- [ ] Solve trunctation globally #1880 

---

### Continuous improvements
- [ ] Expand search design #1031
- [x] Improve modal component #2037 #1962
- [x] Design improvements
  - [x] Improve button component #2030 
- [ ] 💪 Improve "found and cloned" notification #1957
- [x] Remove error notifications on user interaction #1425 
- [x] Improve password input on lock screen #1179 
- [ ] Clicking disabled field #1165 

---

**Legend of annotations**
| Mark | Description |
|------|-------------|
| 🏃 | work in progress |
| ✋ | blocked task |
| 💪 | stretch goal for this iteration |
| 🎨 | design needed |
| 🔵 | more investigation required to remove uncertainty |
| ⚫ | under discussion within the team |
| ⬛ | a large work item, larger than one iteration |

**Comment by rudolfs** [comment]
This cycle was already completed.
