### ISSUE TITLE
Cycle plan: July 26th - August 27th

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2146]
## Plan Items

Below is a summary of the top level plan items.

#### Align projectlists on both profile pages and org pages @juliendonck 
- [ ] Come up with a solution to show following and your projects on the same page #1887  
- [ ] align project list #2089 

#### Navigate to someone else's profile & redesign the profile page @rudolfs 
- [x] Make other user profiles work https://github.com/radicle-dev/radicle-upstream/issues/1874
- [ ] Show attested radicleID on profile and in app #1920 #2091

#### Polish orgs @juliendonck @rudolfs 
- [x] Org ENS integration #2147 @jason
- [ ] Don’t poll Ethereum account data https://github.com/radicle-dev/radicle-upstream/issues/1916
- [ ] Make upstream follow wallet's network https://github.com/radicle-dev/radicle-upstream/issues/2002 @geigerzaehler 
- [ ] 💪 How do we show anchors in the project source browsing screen? https://github.com/radicle-dev/radicle-upstream/issues/1976
- [ ] Improve org loading UX
  - [ ] #2109
  - [ ] #2108 
- [ ] Show anchored state on project page #1976 @juliendonck 
- [ ] Improve org infrastructure
  - [ ] #2171
  - [ ] #2170
  - [ ] #2169

#### Test Ethereum features @geigerzaehler 
- [ ] Write some basic smoke tests for Ethereum related features (orgs, attestations, or token streams) #1921 (@geigerzaehler)
- [ ] 💪 Expand test coverage of orgs #2359 (@geigerzaehler)
- [ ] 💪 ~~#1581~~ Test ENS registration feature  #2360 (@geigerzaehler)

---

### Clean up / nice-to-haves
- [ ] #2091
- [ ] Ethereum settings
  - [ ] Surface ethereum end points in settings #2054
  - [ ] Ethereum opt out setting #2053

---

### Engineering tasks
- [x] #2133 (@geigerzaehler)
- [ ] #2160 @geigerzaehler 
- [x] #1855 and the possibly related #1975 (@geigerzaehler)
- [ ] Improve Ethereum infrastructure in the code base (#1921 @geigerzaehler)
  We’ve seen a lot of additions and changes to Ethereum-related features. This has exposed some shortcomings in the current code that we need to address. This will also be required to properly write tests for Ethereum feature.
- [ ] 💪 Continue improving routing 
  - [ ] #1596
  - [ ] #2168
  - [ ] #2109

---

### Design tasks
- [x] #2100
- [ ] Restyling links #1967 

---

### Continuous improvements
- [ ] Expand search design #1031 
- [ ] 💪 Improve "found and cloned" notification #1957
- [ ] Clicking disabled field #1165 
- [ ] Remove unreliable stats 
- [ ] #2122 
- [ ] #2090 
- [ ] #2092
- [ ] #1964 

---

**Legend of annotations**
| Mark | Description |
|------|-------------|
| 🏃 | work in progress |
| ✋ | blocked task |
| 💪 | stretch goal for this iteration |
| 🎨 | design needed |
| 🔵 | more investigation required to remove uncertainty |
| ⚫ | under discussion within the team |
| ⬛ | a large work item, larger than one iteration |

**Comment by geigerzaehler** [comment]
My update

* I’ve found a fix #2133 . The PR on link (https://github.com/radicle-dev/radicle-link/pull/731) is being approved. Then it should be good to merge.
* I’ve collected enough information on #1975 and #1855 to create an issue in link (https://github.com/radicle-dev/radicle-link/issues/734). I’ll make sure this gets looked at.
* I’ve been quite busy with support, especially for orgs. There’s an serious issue with the claims contract (#2158) that I’m working on with @CodeSandwich.

**Comment by rudolfs** [comment]
This cycle is over, here's the next one: https://github.com/radicle-dev/radicle-upstream/issues/2361.
