### ISSUE TITLE
Adopt Radicle CLI libraries

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2432]
This issue is part of #2431.

The objective is to fully integrate the Radicle CLI libraries into the proxy. Only code from `radicle_daemon` remains that is related to networking and the protocol.

We will not use the SSH agent for authentication as part of this work. Instead we will keep the proxy keystore.

See [RFC#696](https://github.com/radicle-dev/radicle-link/blob/master/docs/rfc/0696-p2p-node.adoc) for details on the CLI.

## Tasks

- [x] PoC with one read-only call to a function from the Radicle CLI libraries (#2458)
- [ ] #2459 
- [ ] Integrate source browsing with the CLI libraries.
- [ ] Use the Radicle CLI for all remaining update functionality.
- [ ] Review outstanding issues

**Comment by rudolfs** [comment]
Is this still relevant @geigerzaehler?
