### ISSUE TITLE
Define and evaluate code collaboration process using Upstream

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2712]
We want to evaluate the code collaboration process using Upstream for ourselves and collect insights about it to determine the next steps.

To prepare for this we add a document to the repo that describes the processes of how patches are submitted to and accepted into Upstream for Upstream maintainers. We verify this process by trying it ourselves for one week and collecting problems: What is tedious, what is buggy, what has workarounds, etc. We then prioritize problems and think of improvements

In addition, we create a document that outlines how external people not familiar with Upstream yet can contribute code. (The document is not for external consumption but for us to analyze the user story.) We again verify this user story by trying it ourselves and collect the problems.

We collect feedback in [this document](https://chip-cartwheel-3be.notion.site/Upstream-Collaboration-Workflow-9f04a70ec5c44356ad1b905b193e5f8e).

### Tasks

- [x] Add document that describes our collaboration process using Upstream
- [x] Add document that outlines how external users can contribute to Upstream
- [x] Try out the process ourselves and collect feedback
  - [x] Determine whether we can update patches by force pusing
- [ ] Try out the external contributor story and collect feedback

**Comment by rudolfs** [comment]
> Try out the external contributor story and collect feedback

This last task is already captured by https://github.com/radicle-dev/radicle-upstream/issues/2759.
