### ISSUE TITLE
Use push/pull seeds

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2756]
We have [seed services][1] that use Git push/pull instead of the Link P2P protcol to share data. [Radicle Client Tools][2] will use the push/pull mechanism and public seed services by default.

We want Upstream to be able to obtain data from push/pull seeds. That is Upstream should be able to find and replicate projects hosted on push/pull seeds.

Furthermore, Upstream should be able to push project data to these seeds so that it is available even if the p2p network is not working.

## Tasks

- [x] ~~Map out the concrete behavior we expect Upstream to have with respect to push/pull. This should consider default seeds and their configuration.~~
- [x] Write out user flows for stories 1 and 2.
- [ ] Create user flows for story 8
- [x] https://github.com/radicle-dev/radicle-upstream/issues/2769
- [x] https://github.com/radicle-dev/radicle-upstream/issues/2777

See [this living document](https://radicle-upstream.notion.site/Upstream-push-pull-integration-1f835058a470452da41a69c4473eb765) for more up-to-date user stories, flows, and specification.

## General Principles

1. Users expect to be able to have continuity between the Upstream, the `rad` binary, meaning their actions in one client should be reflected in the other.
2. Users expect to have single identities that can be accessed across all Radicle clients.

## User stories

1. ✅ As a user with an identity created by Upstream I want to create and publish a project with the `rad` CLI using that identity. (already working)
2. ✅ As a user with an identity created by `rad` I want to start using Upstream. I expect Upstream to use the identity created by `rad`. I expect Upstream to show the projects I created with `rad`. (already working)
3. ✅ As a user I want to add a project to Upstream that was created with `rad` and hosted on a push/pull seed. Projects added in this manner should have the same behavior as projects found in the P2P network. In particular, I can inspect their code in Upstream and check them out locally (#2769)
4. ✅ As a user I want to receive updates on projects updated via the client tools and hosted on a push/pull seed. If another user makes changes to their project and pushes them to a seed I should see these changes in Upstream after a short time.   (#2769)
5. ✅ As a user I want to get update from peers for projects I’ve checked out with Upstream using `rad sync` from `radicle-client-tools`.  (#2769)
6. As a user I want to push my copy of projects in Upstream to a push/pull seed so that others can see them, too.
7. ✅ As a user I don’t want to have to type in my password again when starting Upstream after I already logged in with `rad auth`. (fixed in https://github.com/radicle-dev/radicle-upstream/commit/5bff592ab99f47c5d51aa28c875d7f1d4e19e322)
8. As a user I want my patches to be published using push/pull seeds.

**Comment by rudolfs** [comment]
This can be closed, right @geigerzaehler?
