### ISSUE TITLE
Overview: Orgs I

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#277]
### UI
- [x] sidebar: list orgs "I am a member of"
- [x] modal: org registration
- [x] org profile
  - [x] needs: handle, avatar
  - [x] list projects registered under the org
  - [x] list members registered under the org
- [x] modal: create/register a project under an org (and adjust the modal for project creation under a user along the way) (#285)
- [x] modal: register a member under an org
- [ ] block certain actions according to transaction state, show tooltip spinner & badge on finish (#269)

### Proxy
- [x] Query
  - [x] org (#300)
  - [x] list orgs I am a member of (#309, #340)
  - [x] list projects of an org (#343 )
  - [x] ~listTransactions: add new messages of mutations~ (transaction and member handling moved to separate issues #349 #347 )
- [x] Mutation
   - [x] register org (#300)
   - [x] create/register a project under an org (they already exist as separate mutations)
- [x] ~transactions: permissions, errors, progress, "receiver"~ (#225) (transaction and member handling moved to separate issues #349 #347 )

For more info see #171

**Comment by MeBrei** [comment]
This is a first draft of the related schema. Some of it is already implemented and/or adjusted.

```gql

type Org {
  id: ID!
  avatarFallback: Avatar!
}

type Member {
  handle: ID!
  orgId: ID!
  timestamp: String!
}

union Message = ... | OrgRegistrationMessage | OrgUnregistrationMessage | ProjectRegistrationMessage | MemberRegistration

"""Kind of the transaction message."""
enum MessageKind {
  ...

  """Registration of a new member."""
  MEMBER_REGISTRATION
}

type UpstreamMutation {
  ...
  registerProject(projectName: String!, orgId: String!, maybeLibradIdInput: ID): Transaction!
  registerMember(handle: ID!, orgId: ID!): Transaction!
}

type UpstreamQuery {
  ...
  avatar(handle: ID!, usage: AvatarUsage!): Avatar!
  project(id: ID!): Project!
  projects: [Project!]!
  """List of projects on the registry by id (org or user)"""
  listRegistryProjects(id: ID!): [ID!]!
  """Lists all orgs the handle is a member of"""
  orgs(handle: ID!): [Org!]!
  """Returns the org if it exists"""
  org(id: ID!): Org
  """Returns all registered members of an org"""
  members(id: ID!): [Member!]!
}

"""Context data for a project registered under an Org."""
type OrgRegistration {
  """The id of the Org."""
  orgId: ID!
}

"""Contextual information for an org registration message."""
type OrgRegistrationMessage {
  """Field to distinguish [`Message`] types."""
  kind: MessageKind!

  """The ID of the org."""
  orgId: ID!
}

"""Contextual information for an org unregistration message."""
type OrgUnregistrationMessage {
  """Field to distinguish [`Message`] types."""
  kind: MessageKind!

  """The ID of the org."""
  orgId: ID!
}

union ProjectRegistration = OrgRegistration | UserRegistration

"""Contextual information for a project registration message."""
type ProjectRegistrationMessage {
  """Field to distinguish [`Message`] types."""
  kind: MessageKind!

  """Actual project name, unique under org."""
  projectName: ID!

  """The org under which to register the project."""
  orgId: ID!
}

"""Payload of a member registration message."""
type MemberRegistrationMessage {
  """Field to distinguish [`Message`] types."""
  kind: MessageKind!

  """The unique handle of the user to be registered."""
  handle: ID!

  """The id of the org."""
  orgId: ID!
}
```

**Comment by rudolfs** [comment]
Most of it is done, the rest is tracked in the `Orgs I` milestone as follow-up issues: #347, #269, #349, #347.
