### ISSUE TITLE
Patch Commenting

### ISSUE THREAD

**Issue by Kaihuang724** [radicle-dev/radicle-upstream#2796]
This is all the work needed to implement commenting for patches. This epic will explicitly be for creating and managing comments on patches within Upstream. CLI integration will be excluded from this epic.

User Map and Stories: https://www.figma.com/file/dA7pRJKjVs53hdDhWuHTXu/Story-Maps?node-id=0%3A1

## User Stories
**All Users**
- [x] I need to be able to provide simple text comments.
- [x] I need to be able to format my text appropriately so that I can ensure that my comment is clear.
- [ ] I need to be able to attach files to my comment so that I can give clear context to readers.
- [ ] I want to be able to easily format my text so that I can still effectively style it without knowing Markdown.
- [ ] I want to be able to reference users in my comment so that they’re aware that they need to review the comment.
- [ ] I want to see all the comments in a patch that I have visibility into.
- [ ] I want to be able to see when a patch has a new comment since the last time I reviewed so that I can easily determine if I need to review it.
- [ ] I want to know when someone responds to my comment so that I know that I need to review and reply.
- [x] I want to be able to quote a certain part of a comment so that I can provide context to what I’m responding to.
- [ ] I want to see a timeline of all comments and patch updates so that I can see the general progression of the patch.

**Core Member**
- [ ] I need to be able to quickly find the patch name and description so that I can understand the problem the patch is trying to fix.
- [x] I want to be able to make general comments on the patch itself so that I might be able to clarify what the goal(s) are.
- [x] I want to be able to see all the commits for a patch so that I can see the progress of the fix.
- [ ] I need to be able to see all the code changes within a patch so that I can quickly spot any concerns.
- [ ] I need to be able to make comments on specific lines of code so that I can specify which lines might have issues.
- [ ] I want to be able to make comments on a specific file so that I can make general comments that might be relevant for the whole file.
- [ ] I need to be able to link directly to my comment so that I can share it in any communication channel.

**Contributor**
- [ ] I want to be notified when a core member comments on my patch so that I know I need to review it.
- [x] I want my comment to be available to all the peers that have added me so that they can see the full conversation.
- [ ] I want to be able to see all the comments within context of the parent comment and replies so that I can get the full picture of the conversation.
- [ ] I want the updates in my patch to address certain comments so that the core member knows when a comment has been addressed.
