### ISSUE TITLE
Feature: Transactions

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#347]
Outstanding tasks to complete transactions.

**proxy**

- [x] poll for latest block height and update transactions in cache accordingly (#407)
- [x] extend transaction states with error variants (#407)
- [x] clarify transaction state machine (#407)
- [x] consistent timestamps in status variants (#407)
- [ ] pass additional contextual data (i.e. full user/identity)
- [x] delete receiver
- [ ] control actions depending on tx state
- [x] persist txs cache to disk

**ui**

- [x] polling transaction states and update the transaction center and detail view accordingly (#407)
- [x] once in place in the proxy, handle status/progress/error & transaction costs in the ui (#407)
- [x] animate the transaction center: slide up/down of cards, slide in of the whole center on first transaction
- [x] extract receiver from message (407)
- [ ] control actions depending on tx state (#269)
- [x] more nuanced subject formatting (#346)

Part of #277

**Comment by xla** [comment]
Done.
