### ISSUE TITLE
Feature: Settings

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#385]
Section for the user to change parameters controlling appearance, behaviour and state of the application.

**proxy**
- [x] extend session with settings (#383)
- [x] provide endpoint to update settings parameters (#383)
- [x] provide endpoint to clear cache data (txs, etc.) (#389)
- [x] provide endpoint to clear session (#389)

**ui**
- [x] implement settings screen ui (#375)
- [x] wire up session/settings store (#390)
- [x] save new settings on change (#390)
- [x] use settings data to change app appearance (#390)
- [x] wire up destructive actions (#390)
