### ISSUE TITLE
ui: Navigation/Routing refactor

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#754]
# Navigation Refactor

We have accumulated a plethora of issues which stem from our current routing
strategy and/or the libraries we use. To address this a strategy has been
devised to build up a simple scheme to support our needs and play into the
abstractions we have been established.

## Tracking issues

* #148
* #542
* #648
* #650

## TODOS

* [ ] Implement View based routing (#622)
* [ ] Implement new Overlay
* [ ] Implemetn new global dropdowns
* [ ] Document architecture and usage

#### constraints

* built around native Svelte components
* nested navigations (i.e. Screen 1:N Fragment)
* optionally prefetching before navigating to/rendering
* optionally pass of typed props
* easy to extend for helper code to build reoccurring nav elements.

At the core is the concept of a `View` which represents a parameterised and
prepared component. A map of views and their typed keys as the datastructure
will make it possible to construct a `Navigation` that holds the history of
views and allows - when constructed as a singleton - to be easily advanced from
any component. Such a `Navigation` will be passed to a `Router` component which
owns the rendering of the latest `View` and can be used in Svelte natively.

``` typescript
// src/view.ts

export Component extends SvelteComponent {
  readonly key: K;
  readonly prefetch()?: Promise<void>;
}

export type Props = Record<string, 0 | string>;
export type Map<Key extends string> = Required<Record<Key, Component>>;

export interface View<K extends string> {
  readonly component: Component;
  readonly key: K,
  readonly props?: Props;
  readonly prefetch()?: Promise<void>;
}

export interface Navigation<K extends string> {
  readonly current: Readable<View<K>>;
  back(): void;
  set(key: Key, props?: Props): void;
}

export const create = <K extends string, C extends typeof SvelteComponent>(
  componentMap: Map<K, C>,
  initial: K
): Navigation<K> => {
  const hist = history.create<View<K>>({
    component: componentMap[initial],
    key: initial,
  });

  return {
    current: hist.current,
    back: (): void => {
      hist.pop();
    },
    set: (key: K, props?: Props): void => {
      const component = componentMap[key];

      if (component.prefetch) {
        await component.prefetch();
      }

      hist.push({
        component: component,
        key,
        props,
      });
    },
  };
};
```

``` svelte
<!-- View/Router.svelte --->

<script lang="ts">
  import * as view from "../src/view";

  export let nav: view.Navigation<string>;
  const current = nav.current;
</script>

{#if $current.props}
  <svelte:component this={$current.component} {...$current.props} />
{:else}
  <svelte:component this={$current.component} />
{/if}
```

#### constraints

* at most one displayed at a time
* should be rendered in front of any Screen displayed

**Comment by rudolfs** [comment]
I'm not entirely sure #648 and #560 are related to routing/navigation.

**Comment by xla** [comment]
> I'm not entirely sure #648 and #560 are related to routing/navigation.

#560 was meant to be #650. Corrected. Otherwise they all in the same problem space and need to be globally managed and addressed. To not only preven these bugs but also enable other use-cases like visual transitions.

**Comment by rudolfs** [comment]
Closed by: https://github.com/radicle-dev/radicle-upstream/pull/1876.
