### ISSUE TITLE
Audit coco use of PeerApi methods to contribute back to protocol

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#890]
A declared goal of using high-level abstractions like `PeerApi` from librad was to find out what patterns emerge and extend the `PeerApi` with those, so other user of the library benefit from it. We ought to audit our current use of it in the coco crate and move things upstream. The place at time of writing to be audited, stemming from https://github.com/radicle-dev/radicle-upstream/pull/881#issuecomment-690958979:

https://github.com/radicle-dev/radicle-upstream/blob/ccfa9a4842b676d42f6dd76b7dbbaa6104a7b9f4/proxy/coco/src/peer.rs#L56-L508

**Comment by FintanH** [comment]
@xla, @kim, and I met today to discuss some topics around how we use radicle-link in proxy and how we should proceed for the future. I'm going to layout the discussions here.

**Mutex**

Currently, we have a `Mutex` wrapping the `PeerApi`. For context, this decision was made so that we could use the `PeerApi`'s functionality for our HTTP endpoints. `PeerApi` is only `Send` but not `Sync`, where both are needed to interact with `warp`. Wrapping it in `Mutex` solved this for us -- but brings its own issues. Also noting here that `PeerApi` is not `Send + Sync` because the underlying `Storage` is not `Send + Sync`, otherwise it would be.

The way forward here is that we should use a resource pool solution (think database connections). The `Storage` is allocated on some resource pool where we then borrow handles to it when we want to read/write.

**Storage API**

Segueing from the above, we also noted that the `Storage` API has a large surface area and contains a lot of low-level operations. Since `Storage` is the backbone, a lot of different functions get mixed together and becomes a cognitive drain.

Our thoughts here is that we want to split this into different domains, that are all backed by the storage. For example, we would interact with some kind of `UserStorage` which provides an API to get, list, etc. `User`s. The same would go for `Project`s.

**Networking + Storage**

Following this point, there are functions such as `fetch` and `clone` that require the networking to be running for us to perform those operations. This is implicit and it might make the API more intuitive if we make this more explicit. For example, we would have our `UserStorage` above and equipping it with the capability of networking would give us a `UserStorageFetchableFactory` (did I hear someone say effect-systems at the back?!)

**Mocking**

It's hard to mock `Storage` layouts, which we would like for things like:
* Testing selecting revisions from other peers
* Testing having tracked but not contributed to projects

One idea is having the radicle-link fetcher be able to take a mock fetcher that doesn't need networking but rather can do it via the file-system.

**Testnet**

We haven't been able to use the testnet code properly because it uses `Peer` directly whereas in proxy we've mostly worked with `PeerApi`. One goal of this audit should be to be able to use this testnet code. And this could also be a better solution to above. If it's easier to spin up peers and clone + fetch then we don't need to worry about having `Storage` laid out in a certain way.

**Protocol Resources**

An important point that was brought up was that the `Protocol` needs an exclusive handle to the `Storage`, so it can't compete over a resource pool. Fetch and clone, however can use a resource pool.
Later it was mentioned that the protocol and upstream might have an aligned interest here: **Resource Queues**. If we were to go this route it would need to go through a decision process (RFC) and be thoroughly designed. As mentioned, these things are hard to reason about [insert your favourite queue quote here].

This also brings up the question, do we have two resource pools? One managed by proxy and one managed by the protocol. This brings up further questions around the management of these pools.

**Global Filesystem Paths**

Something that was mentioned in passing was the story around who owns what XDG_CACHE_HOME_WHATEVER and how they're organised. For example, the rad-remote-helper needs to know about where the encrypted secret key lives.

**TODOs**

- [ ] Update the documentation around `local::transport::register`
- [ ] Ensure that when creating a project/user in librad it does a `has_urn` check
- [ ] Ensure that setting `rad_self` for projects is done in librad

**Comment by kim** [comment]
> We haven't been able to use the testnet code properly because it uses Peer directly whereas in proxy we've mostly worked with PeerApi.

Wait, what?

```rust
pub async fn run_on_testnet<F, Fut, A>(peers: Vec<TestPeer>, min_connected: usize, mut f: F) -> A
where
    F: FnMut(Vec<(PeerApi<SecretKey>, SecretKey)>) -> Fut,
// ---------------^^^^^^^
    Fut: Future<Output = A>
```

Is it the other way round?

**Comment by FintanH** [comment]
Ya, but you're passing in `TestPeer` which wraps over `Peer`. Worse yet, in proxy it's actually `Mutex<PeerApi>` :sweat_smile:

**Comment by kim** [comment]
@FintanH I don't understand what the problem -- you do `setup` or `setup_disconnected`, and pass the result to `run_on_testnet`. _Everything else_ is supposed to happen inside that closure.

**Comment by FintanH** [comment]
> I don't understand what the problem is

The problem is that I was being a short-sighted dopfkopf!!!!! Originally the previous iteration of `State` was setting up the run loop and all that jazz. But now it's not.

Indeed WE CAN use the testnet and here's the first test to transition to it: https://github.com/radicle-dev/radicle-upstream/blob/fintan/testnetz/proxy/coco/tests/replication.rs#L15-L74

**Comment by geigerzaehler** [comment]
@FintanH says that all of this work is tracked in the “Thank you, next” project.
