### ISSUE TITLE
feat(ui): Integrate eth wallet using walletconnect

### ISSUE THREAD

**Issue by NunoAlexandre** [radicle-dev/radicle-upstream#940]
As a replacement of the Radicle Registry, we want to integrate an Eth wallet in our application using `walletconnect`.

### TODO

- [x] Re-enable the wallet section
- [ ] Rename 'Wallet" to "Funding"
- [ ] Handle the connection to a wallet
   - [x] Connect
     - [ ] Timeout after X seconds with relevant error message 
   - [x] Disconnect
- When a wallet is connected
   - [x] React to user changing accounts in their wallet app
   - [ ] Handle disconnections
   - [ ] Handle wallet with 0 accounts

**Comment by NunoAlexandre** [comment]
@juliendonck we need a design for the "handle connected to a wallet bit".

Meaning:
- When we don't have a wallet connected, the wallet section is "empty" and should offer a "Connect" button
- When it is _connecting_, it needs to reflect that ongoing task
- When it is `connected`, a `Disconnect` button should be offered

We should also offer a "Forget" button when _connected_ because connecting after disconnecting will not provide a QR code to connect from sktratch but it will try to connect to the previously connected wallet.

**Comment by NunoAlexandre** [comment]
Superseded by #974
