### ISSUE TITLE
Add display name and project name max length validations

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#954]
While reviewing https://github.com/radicle-dev/radicle-upstream/pull/953, I noticed that we don't have any validations for the maximum length of **display name** and **project name**.

- Having a very long **display name** leads to UI breakage:

<img width="50%" alt="Screenshot 2020-09-23 at 16 37 32" src="https://user-images.githubusercontent.com/158411/94028421-271b4900-fdbc-11ea-8bcf-a21bc797070a.png">

- very long project names lead to either the UI looking broken or even a `File name too long` backend error:
<img width="50%" alt="Screenshot 2020-09-23 at 16 49 23" src="https://user-images.githubusercontent.com/158411/94029141-cb04f480-fdbc-11ea-93fb-2a934b9889f4.png">

```
 ERROR api::http::error      > Rejection([MethodNotAllowed, Coco(Git(Error { code: -1, klass: 2, message: "failed to stat \'/Users/rudolfs/work/Lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-Vestibulum-lacinia-dolor-vel-ex-dictum-sed-luctus-nisi-euismod-Maecenas-pellentesque-nibh-accumsan-tellus-porttitor-et-pharetra-lectus-pharetra-Sed-at-tincidunt-eros-Proin-semper-neque-sem-sed-dictum-ex-bibendum-vitae-Curabitur-in-finibus-ante-Nulla-suscipit-urna-sit-amet-sem-mollis-sodales-pretium-odio-cursus-Cras-suscipit-mattis-neque-Fusce-at-lectus-leo-Cras-rutrum-ultricies-fermentum\': File name too long" }))])
```

### TODO

- [x] Validate display and project name max length
- [x] Validate project name (platform-dependent as it is used to create a directory with the same name)
- [ ] make sure the UI shows *display name*, *project name* and *project description* gracefully even when they're at their respective max lengths (get input from @radicle-dev/product on how it should look like)

**Comment by rudolfs** [comment]
What should the maximum lengths be for these attributes @kim, @cloudhead?

**Comment by xla** [comment]
@rudolfs Most file-systems have a max length of 255 characters.

**Comment by rudolfs** [comment]
> @rudolfs Most file-systems have a max length of 255 characters.

We could use that as the upper bound, unless `radicle-link` has a lower limit on project name metadata.
I wonder if the project name limit should not be even lower for UX reasons? \cc @juliendonck @brandonhaslegs

**Comment by NunoAlexandre** [comment]
I checked how Github approaches this and I could create a project with a rather long name. The UI could go around this by truncating long words, so it doesn't need to be the driving factor. File-system and cross-platform issues should. On that, I'd assume that a project name should be compatible as a dir name on any platform or else checking out a project on a different platform it was created in would potentially fail.

**Comment by rudolfs** [comment]
According to our [radicle-link spec](https://github.com/radicle-dev/radicle-link/blob/master/spec/radicle-link.md#project) the limits on the protocol level are:
```
project = {
        ...
        ; Short name of the project, e.g. "linux"
        ? name: tstr .size 32,

        ; Brief description
        ? description: tstr .size 255,
    }

```

```
    user_profile = (
        nickname: tstr .size 32,
        ? full-name: tstr .size 64,
        ...
    )
```

And in the concrete implementation it seems like it's a `String` (if I followed the code correctly):
https://github.com/radicle-dev/radicle-link/blob/master/librad/src/meta/entity/data.rs#L228

@kim is the spec still relevant?

**Comment by cloudhead** [comment]
I don't see a good reason to have names longer than 32 characters, but I do see potential issues in having them. So I'd cap them at 32 in the app.

**Comment by rudolfs** [comment]
@cloudhead: we also have to keep in mind that project names are also tied to the directory which is created on disk when a project is created. This also applies to adding an existing repository as a new project. Meaning -- if an existing repo lives in a folder which is longer than 32 chars, it won't be possible to create a project from it unless you rename the folder.

**Comment by rudolfs** [comment]
@cloudhead and what about the project description?

**Comment by rudolfs** [comment]
For posterity: project description was decided to be 256 chars long.
