### ISSUE TITLE
Wire up waiting room with search

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#984]
In our haste to wire up the search feature, we cut a few corners in https://github.com/radicle-dev/radicle-upstream/pull/969.

Tasks that come to mind that we need to do:
- [ ] Load the `WaitingRoom` on startup
- [ ] Save the `WaitingRoom` (but not sure where and when)
- [x] `request` endpoint should be `PUT` [#1026]
- [x] Check that URN exists in the monorepo before searching [#1030]
- [x] Return the request metadata to the frontend [#1103]
- [x] show list of requests [#1104]
- [x] update progress of requests [#1117]
- [x] emit completion notification [#1117]

**Comment by xla** [comment]
Superseded by #1147 #1148
